### ISSUE TITLE
Configuring the bugsnag hook

### ISSUE THREAD

**Issue by edencorbin** [cludden/sails-hook-bugsnag#1]
I'm trying to get uncaught exceptions to auto send to bugsnag in sails apps, and this hook may be the ticket. I installed via 

```
npm install --save sails-hook-bugsnag
```

I also added/configured the /config/bugsnag.js replacing BUGSNAG_APIKEY with my API key.

I have tested bugsnag node module and the following works: 
var bugsnag = require("bugsnag"); 
bugsnag.register("MYAPIKEY"); 
bugsnag.notify(new Error(string));

But I was hoping the hook might enable automatic logging of uncaught exceptions, perhaps I'm confused about that and the hook is actually working or needs be called?

Thank you for the plugin/support.

**Comment by cludden** [comment]
Hey @edencorbin, bugsnag should automatically capture uncaught exceptions.. is it not working?

**Comment by cludden** [comment]
this is what I'm referring to: https://github.com/bugsnag/bugsnag-node/blob/master/lib/bugsnag.js#L74

**Comment by edencorbin** [comment]
I have gotten this to work, nothing is not defined and crashes sails, properly sending a notification to Bugsnag, anywhere inside the wrapper function, 

```
      Err: function (req, res, next){
          bugsnag.autoNotify(function(){
            nothing.crash;
            res.send(400);
          });
      },
```

However, I would have to call this on every action/route to get it application wide, I'm looking for a more elegant way to accomplish that, the bugsnag docs point to setting it up via middle-ware, however that's where I'm struggling and thought this hook might help. Is there some place to configure Bugsnag app wide I am missing?

**Comment by cludden** [comment]
I might be confused with your issue. The hook calls #register on bugsnag which automatically sets up the capturing of uncaught exceptions. You should not need the #autoNotify. We're using this hook in production and it is handling uncaught exceptions as expected. If you don't use the #autoNotify wrapper, is it not notifying the error?

**Comment by edencorbin** [comment]
Firstly, thanks so much for the help, I'm about 99%+ sure its user (me) error. Correct, it doesn't send the bug to bugsnag, let me describe all steps I take as there aren't many and I'm likely missing something simple. First I install bugsnag by including in my package as "bugsnag": "~1.7.0" and running npm install in root sails project, then I run npm install --save sails-hook-bugsnag in my root sails project, then I create a bugsnag.js configuration file in my /config folder and use the following contents:

```
    module.exports.bugsnag = {
        apiKey: 'MYKEY', // required, note I don't use process.env, just hard coding key as string
        enabled: true, // note your example may be missing a comma here
        options: {
            // pass configuration options to bugsnag
            // see https://github.com/bugsnag/bugsnag-node for more examples
        }
    };
```

MYKEY of course being my actual API key that works via directly using simple methods from bugsnag in the sails project. Then I run the error scenario above, and the app errors, but there is no bug sent to bugsnag.

**Comment by cludden** [comment]
hmmm, is your NODE_ENV production? I think by default, bugsnag only sends notifications when NODE_ENV = production. Although you did mention that it was sending the errors when you used #autoNotify, right?

**Comment by cludden** [comment]
try modifying /api/responses/serverError.js and adding a call to sails.bugsnag.notify() there, that should be called for all uncaught errors in controllers

**Comment by cludden** [comment]
actually now that I look into it, I think you're correct in that the "router:request:500" event is not firing.

try adding this to your `config/bootstrap.js` file:

``` javascript
module.exports.bootstrap = function(cb) {
    // ..
    sails.on('router:request:500', function(err, req) {
        sails.bugsnag.notify(err, {
            request: req
        });
    });
    // ..
    cb();
}
```

**Comment by edencorbin** [comment]
That worked, many thanks from me and my team! I'm doing some tests on if its --prod or the call to and sails.bugsnag.notify() in /api/responses/serverError.js, or both and will update this ticket shortly!

**Comment by edencorbin** [comment]
Okay, it looks like --prod was the trick, although adding the calls to serverError is good to know about too. I'm partial face palming, but I don't recall anywhere saying bugsnag needs to be run in production, is that the case for all sails hooks?

**Comment by cludden** [comment]
Awesome! FYI, from the bugsnag docs:

**releaseStage**
By default, Bugsnag looks at the NODE_ENV environment variable to see what releaseStage the script is running in. If that is not set, Bugsnag assumes you are running in production. If you want to override this behavior, you can set the releaseStage option:

```
bugsnag.register("your-api-key-here", { releaseStage: "development" });
```

**notifyReleaseStages**
By default the notifier will notify Bugsnag of production and development exceptions. If you wish to be notified about production exceptions only, you can set the notifyReleaseStages option.

```
bugsnag.register("your-api-key-here", { notifyReleaseStages: ["production"] });
```

you can have bugsnag notify in other environments by adding them to the _notifyReleaseStages_ array like so:

```
module.exports.bugsnag = {
        apiKey: 'MYKEY',
        options: {
            notifyReleaseStages: ['development', 'staging', 'production']
        }
    };
```
